#!/usr/bin/env Rscript
# Created by Hongjun Li
# Modified by Richard

library("argparse")
library("pROC")
library("RColorBrewer")
#color=c("#8968CD","#7EC0EE","#6B8E23","#436EEE","#218868","#27408B","#7CCD7C","#CD853F","#CD4F39","#CD69C9","#FF8247","#8B0A50","#388E8E","#636363","#8B3A3A","#8B864E","#FFF0F5","#8B8386","#BFFFFF","#F08080","#7A8B8B","#8470FF","#C0FF3E")
#color<-c(brewer.pal(12,"Set3"), brewer.pal(8,"Set2"))
color<-c("#000000", "#FF3366", "#00CC00", "#0066CC")
# create parser object
parser <- ArgumentParser(description='Plot roc curve of mei model and single taxa.')
# specify our desired options
# by default ArgumentParser will add an help option
parser$add_argument("-m", "--model_score", type="character", nargs=1, required=TRUE,
                    help="model score list generated by the training step")
parser$add_argument("-f", "--features_abd", type="character", nargs=1, required=TRUE,
                    help="Features abundance table")
parser$add_argument("-n", "--niche", type="character", nargs=1, required=TRUE,
                    help="sample host niche(human or environment) for plot")
# get command line options, if help option encountered print help and exit,
# otherwise if options not found on command line then set defaults,
args <- parser$parse_args()

model_score_matrix = read.table(args$model_score, header = TRUE)
features_abd_matrix = read.table(args$features_abd, header = TRUE)

# def function
plotRoc <- function(label, score, i, j)
{
    plot.roc(label, score, auc = TRUE, col = color[1], lty = 1, print.auc=FALSE, lwd = 3)
}

addLineToRoc <- function(label, score, i, j)
{
    lines.roc(label, score, col = color[i], lty=j, lwd=2)
}

plotRatio <- function(label, score)
{
    lines.roc(label, score, col = color[4], lty = 2, lwd = 3)
}
# plot roc of mei model
#count = 1
for(i in 2:ncol(model_score_matrix))
{
    #count = count + 1
    plotRoc(model_score_matrix[,1], model_score_matrix[,i], '1', 1)
}

# plot roc of single feature based on abundance
colNo <- c(color[1])
colLty <- c(1)
lwdNo <- c(3)
colName <- c('model_score')
count = 1
colorl = 2
featureLen = ncol(features_abd_matrix)
if(args$niche == "human"){
    plotRatio(features_abd_matrix[,1], features_abd_matrix[,featureLen])
    colNo <- c(colNo, color[4])
    colLty <- c(colLty, 2)
    lwdNo <- c(lwdNo, 3)
    colName <- c(colName, 'p__Bacteroidetes/p__Firmicutes')
    featureLen = featureLen - 1
}
last = strsplit(colnames(features_abd_matrix)[2], "_")[[1]][1]
for(i in 2:featureLen)
{
    count = count + 1
    now = strsplit(colnames(features_abd_matrix)[i], "_")[[1]][1]
    if(last != now){
        count = 2
        colorl = 3
        last = now
    }
    colNo <- c(colNo, color[colorl])
    colLty <- c(colLty, count)
    lwdNo <- c(lwdNo, 2)
    addLineToRoc(features_abd_matrix[,1], features_abd_matrix[,i], colorl, count)
}

# add legend
# colNo <- c('1')
# colLty <- c(1)
# for(i in 2:count)
# {
#     colNo <- c(colNo, as.character(i+1))
#     colLty <- c(colLty, i)
# }

colName <- c(colName, colnames(features_abd_matrix)[2:featureLen])

legend("bottomright", legend=colName, col=colNo, lty=colLty, lwd=lwdNo, cex = 1.2)
